import { CalendarDays, Database, Download, Gauge, Map, Timer, TrendingDown, TrendingUp } from 'lucide-react';
import { useState } from 'react';
import PanelState from '../components/PanelState';
import StatCard from '../components/StatCard';
import { useReport } from '../hooks/useReport';

const numberFormatter = new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 });

function ReportPage() {
  const { data, isLoading, error } = useReport();
  const [exportRequested, setExportRequested] = useState(false);

  if (isLoading) {
    return <section className="mx-auto w-full max-w-[1400px] px-5 py-8 sm:px-8"><div className="h-10 w-72 animate-pulse rounded-lg bg-white/[0.06]" /><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-36 animate-pulse rounded-2xl bg-card" />)}</div></section>;
  }
  if (error) {
    return <section className="mx-auto w-full max-w-[1400px] px-5 py-8 sm:px-8"><PanelState title="Report unavailable" message={error} tone="error" /></section>;
  }

  const report = data?.report;
  if (!report) {
    return <section className="mx-auto w-full max-w-[1400px] px-5 py-8 sm:px-8"><PanelState title="No report data" message="The report API returned no summary." /></section>;
  }

  const stats = [
    { label: 'Total records', value: numberFormatter.format(report.total_records), icon: Database, accent: 'bg-blue-400/10 text-blue-300' },
    { label: 'Average consumption', value: numberFormatter.format(report.average_consumption), suffix: 'kWh', icon: Gauge, accent: 'bg-emerald-400/10 text-emerald-300' },
    { label: 'Maximum consumption', value: numberFormatter.format(report.maximum_consumption), suffix: 'kWh', icon: TrendingUp, accent: 'bg-amber-400/10 text-amber-300' },
    { label: 'Minimum consumption', value: numberFormatter.format(report.minimum_consumption), suffix: 'kWh', icon: TrendingDown, accent: 'bg-cyan-400/10 text-cyan-300' },
  ];

  return (
    <section className="mx-auto w-full max-w-[1400px] px-5 py-8 sm:px-8">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-secondary">Reports</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">A clearer view of performance.</h1><p className="mt-2 text-sm text-slate-500">A generated summary of the connected energy dataset.</p></div><button type="button" onClick={() => setExportRequested(true)} className="flex w-fit items-center gap-2 rounded-xl border border-white/[0.08] bg-white/[0.04] px-3.5 py-2.5 text-sm text-slate-300 transition hover:bg-white/[0.08] hover:text-white"><Download size={16} />{exportRequested ? 'Export ready' : 'Export report'}</button></div>
      <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <StatCard key={stat.label} {...stat} />)}</div>
      <div className="mt-8 grid gap-4 lg:grid-cols-2">
        <div className="rounded-2xl border border-white/[0.07] bg-card p-5 sm:p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-400/10 p-2.5 text-blue-300"><Map size={18} /></div><div><h2 className="text-sm font-medium text-slate-200">Dataset coverage</h2><p className="mt-1 text-xs text-slate-500">Scope of the generated report</p></div></div><div className="mt-7 grid grid-cols-2 gap-5"><div><p className="text-xs text-slate-600">Regions tracked</p><p className="mt-2 text-2xl font-semibold text-white">{numberFormatter.format(report.total_regions)}</p></div><div><p className="text-xs text-slate-600">Report status</p><p className="mt-2 text-2xl font-semibold text-emerald-300">{report.status}</p></div></div></div>
        <div className="rounded-2xl border border-white/[0.07] bg-card p-5 sm:p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-amber-400/10 p-2.5 text-amber-300"><Timer size={18} /></div><div><h2 className="text-sm font-medium text-slate-200">Operational patterns</h2><p className="mt-1 text-xs text-slate-500">Records grouped by detected conditions</p></div></div><div className="mt-7 grid grid-cols-2 gap-5"><div><p className="text-xs text-slate-600">Peak-hour records</p><p className="mt-2 text-2xl font-semibold text-white">{numberFormatter.format(report.peak_hour_records)}</p></div><div><p className="text-xs text-slate-600">Weekend records</p><p className="mt-2 text-2xl font-semibold text-white">{numberFormatter.format(report.weekend_records)}</p></div></div></div>
      </div>
      <div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-slate-600"><span className="flex items-center gap-1.5"><CalendarDays size={13} />Latest record: {report.latest_datetime || 'Unavailable'}</span><span>Generated by {report.generated_by}</span></div>
    </section>
  );
}

export default ReportPage;
